[package]
name = "signed"
version = "0.1.0"
edition = "2021"

[dependencies]
theframework = { path = "../TheFramework", features = ["ui"]}
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"